feat: open_pending_fs_bills fix: // adding await below as a fix for: "TypeError: get_sales_invoice_child_table() missing 1 required positional argument: 'sales_invoice_item'"     const sales_invoice_item = await this.invoice_doc.items[0];